  minio:
    image: minio/minio:latest
    container_name: ${minio_container_name}
    environment:
      MINIO_ROOT_USER: ${minio_user}
      MINIO_ROOT_PASSWORD: ${minio_password}
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - ${minio_port1}
      - ${minio_port2}
    volumes:
      - vol:/data
    networks: 
      - netw