  db:
    image: postgres
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes: 
      - vol:/var/lib/postgresql
      - ./src/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORTS}
    networks: 
      - netw

  pgadmin:
    image: dpage/pgadmin4
    container_name: ${PGADMIN_CONTAINER_NAME}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PG_ADMIN_PORTS}
    volumes: 
      - volume_db:/var/lib/pgadmin
    networks: 
      - netw